{% set name = "django-tables2" %}
{% set version = "2.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/jieter/django-tables2/archive/v{{ version }}.tar.gz
  sha256: 7698643bf943333f9339b8e0e8d23fe860785105885820c480edc3daae35ab08

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - django >=3.2,!=4.0

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
    - python -c "import django; from django.conf import settings; settings.configure(); django.setup(); import django_tables2;"

about:
  home: https://github.com/jieter/django-tables2
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: django-tables2 simplifies the task of turning sets of data into HTML tables.
  doc_url: https://django-tables2.readthedocs.io/en/latest/
  dev_url: https://github.com/jieter/django-tables2

extra:
  recipe-maintainers:
    - gscoppino
